// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB18rE-EILu9dLqiLUzbBhmgsdZpVUAugc',
    appId: '1:663283881790:web:c0d178eafa617cf76f7e6f',
    messagingSenderId: '663283881790',
    projectId: 'instagram-clone-a9bdc',
    authDomain: 'instagram-clone-a9bdc.firebaseapp.com',
    storageBucket: 'instagram-clone-a9bdc.firebasestorage.app',
    measurementId: 'G-L7D4VMGXZH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSQD-moamzfhhF_sXzpHNRXJZE-OQAq5Y',
    appId: '1:663283881790:android:012c47bc886112ce6f7e6f',
    messagingSenderId: '663283881790',
    projectId: 'instagram-clone-a9bdc',
    storageBucket: 'instagram-clone-a9bdc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2EjVn40mgNt_As2V2JWJiuZ4I4XjvSiA',
    appId: '1:663283881790:ios:86ad692f46b1a1566f7e6f',
    messagingSenderId: '663283881790',
    projectId: 'instagram-clone-a9bdc',
    storageBucket: 'instagram-clone-a9bdc.firebasestorage.app',
    iosBundleId: 'com.example.instagramClone',
  );
}
